name: Maven Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Compile and Clean
        run: mvn clean compile
        working-directory: maven  # Updated to the correct directory

      - name: Test
        run: mvn test
        working-directory: maven  # Updated to the correct directory

      - name: Deploy
        run: mvn package
        working-directory: maven  # Updated to the correct directory

